"""NIFTY50 stock universe with metadata."""

NIFTY50 = [
    {"symbol": "ADANIENT.NS",   "name": "Adani Enterprises",     "sector": "Energy"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports",            "sector": "Industrials"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals",       "sector": "Healthcare"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints",           "sector": "Consumer"},
    {"symbol": "AXISBANK.NS",   "name": "Axis Bank",              "sector": "Banking"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto",             "sector": "Auto"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv",          "sector": "Finance"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance",          "sector": "Finance"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel",          "sector": "Telecom"},
    {"symbol": "BPCL.NS",       "name": "BPCL",                   "sector": "Energy"},
    {"symbol": "BRITANNIA.NS",  "name": "Britannia Industries",   "sector": "Consumer"},
    {"symbol": "CIPLA.NS",      "name": "Cipla",                  "sector": "Pharma"},
    {"symbol": "COALINDIA.NS",  "name": "Coal India",             "sector": "Energy"},
    {"symbol": "DIVISLAB.NS",   "name": "Divi's Laboratories",    "sector": "Pharma"},
    {"symbol": "DRREDDY.NS",    "name": "Dr. Reddy's Labs",       "sector": "Pharma"},
    {"symbol": "EICHERMOT.NS",  "name": "Eicher Motors",          "sector": "Auto"},
    {"symbol": "GRASIM.NS",     "name": "Grasim Industries",      "sector": "Materials"},
    {"symbol": "HCLTECH.NS",    "name": "HCL Technologies",       "sector": "IT"},
    {"symbol": "HDFCBANK.NS",   "name": "HDFC Bank",              "sector": "Banking"},
    {"symbol": "HDFCLIFE.NS",   "name": "HDFC Life Insurance",    "sector": "Finance"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp",          "sector": "Auto"},
    {"symbol": "HINDALCO.NS",   "name": "Hindalco Industries",    "sector": "Materials"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever",     "sector": "Consumer"},
    {"symbol": "ICICIBANK.NS",  "name": "ICICI Bank",             "sector": "Banking"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank",          "sector": "Banking"},
    {"symbol": "INFY.NS",       "name": "Infosys",                "sector": "IT"},
    {"symbol": "ITC.NS",        "name": "ITC Limited",            "sector": "Consumer"},
    {"symbol": "JSWSTEEL.NS",   "name": "JSW Steel",              "sector": "Materials"},
    {"symbol": "KOTAKBANK.NS",  "name": "Kotak Mahindra Bank",    "sector": "Banking"},
    {"symbol": "LT.NS",         "name": "Larsen & Toubro",        "sector": "Industrials"},
    {"symbol": "LTIM.NS",       "name": "LTIMindtree",            "sector": "IT"},
    {"symbol": "M&M.NS",        "name": "Mahindra & Mahindra",    "sector": "Auto"},
    {"symbol": "MARUTI.NS",     "name": "Maruti Suzuki",          "sector": "Auto"},
    {"symbol": "NESTLEIND.NS",  "name": "Nestle India",           "sector": "Consumer"},
    {"symbol": "NTPC.NS",       "name": "NTPC Limited",           "sector": "Energy"},
    {"symbol": "ONGC.NS",       "name": "Oil & Natural Gas Corp", "sector": "Energy"},
    {"symbol": "POWERGRID.NS",  "name": "Power Grid Corp",        "sector": "Utilities"},
    {"symbol": "RELIANCE.NS",   "name": "Reliance Industries",    "sector": "Energy"},
    {"symbol": "SBILIFE.NS",    "name": "SBI Life Insurance",     "sector": "Finance"},
    {"symbol": "SBIN.NS",       "name": "State Bank of India",    "sector": "Banking"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance",        "sector": "Finance"},
    {"symbol": "SUNPHARMA.NS",  "name": "Sun Pharmaceutical",     "sector": "Pharma"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products", "sector": "Consumer"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors",            "sector": "Auto"},
    {"symbol": "TATASTEEL.NS",  "name": "Tata Steel",             "sector": "Materials"},
    {"symbol": "TCS.NS",        "name": "Tata Consultancy Services","sector": "IT"},
    {"symbol": "TECHM.NS",      "name": "Tech Mahindra",          "sector": "IT"},
    {"symbol": "TITAN.NS",      "name": "Titan Company",          "sector": "Consumer"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement",       "sector": "Materials"},
    {"symbol": "WIPRO.NS",      "name": "Wipro Limited",          "sector": "IT"},
]

SYMBOLS = [s["symbol"] for s in NIFTY50]
SYMBOL_MAP = {s["symbol"]: s for s in NIFTY50}
